export const INPUT_PLACEHOLDER = {
	NAME: {
		EN: "Name",
		VI: "Tên",
		ZH: "名称",
	},
	EMAIL: {
		EN: "Email",
		VI: "Email",
		ZH: "电子邮件",
	},
	PASSWORD: {
		EN: "Password",
		VI: "Mật khẩu",
		ZH: "密码",
	},
	PHONE: {
		EN: "Phone",
		VI: "Điện thoại",
		ZH: "电话",
	},
	PROJECT_NAME: {
		EN: "Project Name",
		VI: "Tên dự án",
		ZH: "项目名称",
	},
	INDUSTRY: {
		EN: "Industry",
		VI: "Ngành",
		ZH: "行业",
	},
	EXPERIENCE_LEVEL: {
		EN: "Experience Level",
		VI: "Trình độ kinh nghiệm",
		ZH: "经验水平",
	},
	EDUCATION_LEVEL: {
		EN: "Education Level",
		VI: "Trình độ học vấn",
		ZH: "教育水平",
	},
	CERTIFICATIONS: {
		EN: "Certifications",
		VI: "Chứng chỉ",
		ZH: "证书",
	},
	EXPERTISE: {
		EN: "Expertise",
		VI: "Chuyên môn",
		ZH: "专业",
	},
	COMMITMENT: {
		EN: "Commitment",
		VI: "Cam kết",
		ZH: "承诺",
	},
	LOCATION: {
		EN: "Location",
		VI: "Địa điểm",
		ZH: "地点",
	},
	LANGUAGE: {
		EN: "Language",
		VI: "Ngôn ngữ",
		ZH: "语言",
	},
	SECTOR: {
		EN: "Sector",
		VI: "Ngành",
		ZH: "行业",
	},
	ACCOUNTING_AND_FINANCE: {
		EN: "Accounting and Finance",
		VI: "Kế toán và Tài chính",
		ZH: "会计与金融",
	},
	HUMAN_RESOURCE: {
		EN: "Human Resource",
		VI: "Nhân sự",
		ZH: "人力资源",
	},
	INTERNATIONAL: {
		EN: "International",
		VI: "Quốc tế",
		ZH: "国际",
	},
	LAW_AND_LEGAL: {
		EN: "Law and Legal",
		VI: "Pháp lý",
		ZH: "法律",
	},
	MANAGEMENT: {
		EN: "Management",
		VI: "Quản lý",
		ZH: "管理",
	},
	MARKETING: {
		EN: "Marketing",
		VI: "Marketing",
		ZH: "市场营销",
	},
	OPERATIONS: {
		EN: "Operations",
		VI: "Vận hành",
		ZH: "操作",
	},
	SALES: {
		EN: "Sales",
		VI: "Bán hàng",
		ZH: "销售",
	},
	STARTING_UP: {
		EN: "Starting Up",
		VI: "Khởi nghiệp",
		ZH: "启动",
	},
	TECHNOLOGY_AND_INTERNET: {
		EN: "Technology and Internet",
		VI: "Công nghệ và Internet",
		ZH: "技术和互联网",
	},
	SUSTAINABILITY: {
		EN: "Sustainability",
		VI: "Bền vững",
		ZH: "可持续性",
	},
	STAGE: {
		EN: "Stage",
		VI: "Giai đoạn",
		ZH: "阶段",
	},
	TEAM_ROLE: {
		EN: "Team Role",
		VI: "Vai trò nhóm",
		ZH: "团队角色",
	},
	ROLE: {
		EN: "Role",
		VI: "Vai trò",
		ZH: "角色",
	},
};

export const SECTOR = {
	EN: [
		{ label: "Information Technology", value: "Information Technology" },
		{ label: "Healthcare", value: "Healthcare" },
		{ label: "Consumer Staples", value: "Consumer Staples" },
		{ label: "Material", value: "Material" },
		{ label: "Communication Services", value: "Communication Services" },
		{ label: "Industrials", value: "Industrials" },
		{ label: "Financials", value: "Financials" },
		{ label: "Consumer Discretionary", value: "Consumer Discretionary" },
		{ label: "Utilities", value: "Utilities" },
		{ label: "Real Esates", value: "Real Esates" },
	],
	VI: [
		{ label: "Công nghệ thông tin", value: "Information Technology" },
		{ label: "Chăm sóc sức khỏe", value: "Healthcare" },
		{ label: "Hàng tiêu dùng", value: "Consumer Staples" },
		{ label: "Vật liệu", value: "Material" },
		{ label: "Dịch vụ truyền thông", value: "Communication Services" },
		{ label: "Công nghiệp", value: "Industrials" },
		{ label: "Tài chính", value: "Financials" },
		{ label: "Hàng tiêu dùng", value: "Consumer Discretionary" },
		{ label: "Tiện ích", value: "Utilities" },
		{ label: "Bất động sản", value: "Real Esates" },
	],
	ZH: [
		{ label: "信息技术", value: "Information Technology" },
		{ label: "保健", value: "Healthcare" },
		{ label: "消费品", value: "Consumer Staples" },
		{ label: "材料", value: "Material" },
		{ label: "通讯服务", value: "Communication Services" },
		{ label: "工业", value: "Industrials" },
		{ label: "金融", value: "Financials" },
		{ label: "消费自由", value: "Consumer Discretionary" },
		{ label: "公共事业", value: "Utilities" },
		{ label: "房地产", value: "Real Esates" },
	],
};

export const EXPERIENCE_LEVEL = {
	EN: [
		{ label: "Entry-Level", value: "Entry-Level" },
		{ label: "Junior", value: "Junior" },
		{ label: "Mid-Level", value: "Mid-Level" },
		{ label: "Senior", value: "Senior" },
		{ label: "Executive", value: "Executive" },
	],
	VI: [
		{ label: "Nhập môn", value: "Entry-Level" },
		{ label: "Trung cấp", value: "Junior" },
		{ label: "Trung cấp", value: "Mid-Level" },
		{ label: "Cao cấp", value: "Senior" },
		{ label: "Quản lý cấp cao", value: "Executive" },
	],
	ZH: [
		{ label: "入门级", value: "Entry-Level" },
		{ label: "初级", value: "Junior" },
		{ label: "中级", value: "Mid-Level" },
		{ label: "高级", value: "Senior" },
		{ label: "高管", value: "Executive" },
	],
};

export const EDUCATION_LEVEL = {
	EN: [
		{ label: "College", value: "College" },
		{ label: "Bachelors", value: "Bachelors" },
		{ label: "Masters", value: "Masters" },
		{ label: "PhD", value: "PhD" },
	],
	VI: [
		{ label: "Cao đẳng", value: "College" },
		{ label: "Đại học", value: "Bachelors" },
		{ label: "Thạc sĩ", value: "Masters" },
		{ label: "Tiến sĩ", value: "PhD" },
	],
	ZH: [
		{ label: "大专", value: "College" },
		{ label: "学士", value: "Bachelors" },
		{ label: "硕士", value: "Masters" },
		{ label: "博士", value: "PhD" },
	],
};

export const CERTIFICATION = {
	EN: [
		{
			label: "Professional Certifications",
			value: "Professional Certifications",
		},
		{
			label: "Online Course Certificates",
			value: "Online Course Certificates",
		},
		{ label: "Bootcamps", value: "Bootcamps" },
		{ label: "Consumer Discretionary", value: "Consumer Discretionary" },
	],
	VI: [
		{
			label: "Chứng chỉ chuyên nghiệp",
			value: "Professional Certifications",
		},
		{
			label: "Chứng chỉ khóa học trực tuyến",
			value: "Online Course Certificates",
		},
		{ label: "Bootcamps", value: "Bootcamps" },
		{ label: "Consumer Discretionary", value: "Consumer Discretionary" },
	],
	ZH: [
		{
			label: "专业证书",
			value: "Professional Certifications",
		},
		{
			label: "在线课程证书",
			value: "Online Course Certificates",
		},
		{ label: "Bootcamps", value: "Bootcamps" },
		{ label: "Consumer Discretionary", value: "Consumer Discretionary" },
	],
};

export const COMMITMENT = {
	EN: [
		{ label: "Exploring", value: "Exploring" },
		{ label: "Part-time", value: "Part-time" },
		{ label: "Full-time", value: "Full-time" },
		{ label: "All-In", value: "All-In" },
	],
	VI: [
		{ label: "Khám phá", value: "Exploring" },
		{ label: "Bán thời gian", value: "Part-time" },
		{ label: "Toàn thời gian", value: "Full-time" },
		{ label: "Tất cả", value: "All-In" },
	],
	ZH: [
		{ label: "探索", value: "Exploring" },
		{ label: "兼职", value: "Part-time" },
		{ label: "全职", value: "Full-time" },
		{ label: "全情投入", value: "All-In" },
	],
};

export const LOCATION = {
	EN: [
		{ label: "Viet Nam", value: "Viet Nam" },
		{ label: "Singapore", value: "Singapore" },
		{ label: "United States", value: "United States" },
		{ label: "United Kingdom", value: "United Kingdom" },
		{ label: "Australia", value: "Australia" },
		{ label: "Japan", value: "Japan" },
		{ label: "South Korea", value: "South Korea" },
		{ label: "China", value: "China" },
		{ label: "India", value: "India" },
	],
	VI: [
		{ label: "Việt Nam", value: "Viet Nam" },
		{ label: "Singapore", value: "Singapore" },
		{ label: "Hoa Kỳ", value: "United States" },
		{ label: "Vương quốc Anh", value: "United Kingdom" },
		{ label: "Úc", value: "Australia" },
		{ label: "Nhật Bản", value: "Japan" },
		{ label: "Hàn Quốc", value: "South Korea" },
		{ label: "Trung Quốc", value: "China" },
		{ label: "Ấn Độ", value: "India" },
	],
	ZH: [
		{ label: "越南", value: "Viet Nam" },
		{ label: "新加坡", value: "Singapore" },
		{ label: "美国", value: "United States" },
		{ label: "英国", value: "United Kingdom" },
		{ label: "澳大利亚", value: "Australia" },
		{ label: "日本", value: "Japan" },
		{ label: "韩国", value: "South Korea" },
		{ label: "中国", value: "China" },
		{ label: "印度", value: "India" },
	],
};

export const CITY = {
	EN: [
		{ label: "Ho Chi Minh", value: "Ho Chi Minh" },
		{ label: "Ha Noi", value: "Ha Noi" },
		{ label: "Da Nang", value: "Da Nang" },
		{ label: "Can Tho", value: "Can Tho" },
		{ label: "Hai Phong", value: "Hai Phong" },
		{ label: "Vung Tau", value: "Vung Tau" },
		{ label: "Nha Trang", value: "Nha Trang" },
		{ label: "Da Lat", value: "Da Lat" },
		{ label: "Hue", value: "Hue" },
		{ label: "Quang Ninh", value: "Quang Ninh" },
		{ label: "Phu Quoc", value: "Phu Quoc" },
		{ label: "Hoi An", value: "Hoi An" },
	],
	VI: [
		{ label: "Hồ Chí Minh", value: "Ho Chi Minh" },
		{ label: "Hà Nội", value: "Ha Noi" },
		{ label: "Đà Nẵng", value: "Da Nang" },
		{ label: "Cần Thơ", value: "Can Tho" },
		{ label: "Hải Phòng", value: "Hai Phong" },
		{ label: "Vũng Tàu", value: "Vung Tau" },
		{ label: "Nha Trang", value: "Nha Trang" },
		{ label: "Đà Lạt", value: "Da Lat" },
		{ label: "Huế", value: "Hue" },
		{ label: "Quảng Ninh", value: "Quang Ninh" },
		{ label: "Phú Quốc", value: "Phu Quoc" },
		{ label: "Hội An", value: "Hoi An" },
	],
	ZH: [
		{ label: "胡志明", value: "Ho Chi Minh" },
		{ label: "河内", value: "Ha Noi" },
		{ label: "岘港", value: "Da Nang" },
		{ label: "芹苴", value: "Can Tho" },
		{ label: "海防", value: "Hai Phong" },
		{ label: "Vũng Tàu", value: "Vung Tau" },
		{ label: "芽庄", value: "Nha Trang" },
		{ label: "大叻", value: "Da Lat" },
		{ label: "Hue", value: "Hue" },
		{ label: "广宁", value: "Quang Ninh" },
		{ label: "富国", value: "Phu Quoc" },
		{ label: "会安", value: "Hoi An" },
	],
};

export const AREA_OF_EXPERTISE = {
	EN: {
		Accounting_and_Finance: [
			{ label: "Accounting", value: "Accounting" },
			{ label: "Audits", value: "Audits" },
			{ label: "Bookkeeping", value: "Bookkeeping" },
			{ label: "Cash Flow", value: "Cash Flow" },
			{ label: "Financial Planning", value: "Financial Planning" },
			{ label: "Loans and Financing", value: "Loans and Financing" },
			{ label: "Taxes", value: "Taxes" },
			{ label: "Financials", value: "Financials" },
		],
		Human_Resources: [
			{
				label: "Compensation and Benefits",
				value: "Compensation and Benefits",
			},
			{
				label: "Contractor and Consultants",
				value: "Contractor and Consultants",
			},
			{ label: "Employee Traning", value: "Employee Traning" },
			{ label: "Personnel Policies", value: "Personnel Policies" },
			{ label: "Staffing and Recruiting", value: "Staffing and Recruiting" },
		],
		International: [
			{ label: "Custom and Tariffs", value: "Custom and Tariffs" },
			{ label: "Exporting and Importing", value: "Exporting and Importing" },
			{ label: "Global Markets", value: "Global Markets" },
			{ label: "Outsourcing", value: "Outsourcing" },
		],
		Law_and_Legal: [
			{ label: "Contracts", value: "Contracts" },
			{ label: "Employee/Labour Law", value: "Employee/Labour Law" },
			{ label: "Immigration Law", value: "Immigration Law" },
			{ label: "Intellectual Property", value: "Intellectual Property" },
			{ label: "Property Law", value: "Property Law" },
			{ label: "Tax Law", value: "Tax Law" },
		],
		Management: [
			{ label: "Board Development", value: "Board Development" },
			{ label: "Businness Insurance", value: "Businness Insurance" },
			{ label: "Businness Strategy", value: "Businness Strategy" },
			{ label: "Fundraising", value: "Fundraising" },
			{ label: "Growth and Development", value: "Growth and Development" },
			{ label: "Leadership", value: "Leadership" },
			{
				label: "Planning and Goal Setting",
				value: "Planning and Goal Setting",
			},
			{ label: "Project Management", value: "Project Management" },
			{ label: "Work-life Balance", value: "Work-life Balance" },
		],
		Marketing: [
			{
				label: "Advertising and Promotion",
				value: "Advertising and Promotion",
			},
			{ label: "Branding and Identity", value: "Branding and Identity" },
			{ label: "Business Development", value: "Business Development" },
			{ label: "Distribution", value: "Distribution" },
			{ label: "Market Research", value: "Market Research" },
			{ label: "Marketing Collateral", value: "Marketing Collateral" },
			{ label: "Pricing", value: "Pricing" },
			{ label: "Product Development", value: "Product Development" },
			{
				label: "Puclic Relations and Media",
				value: "Puclic Relations and Media",
			},
			{ label: "Social Media", value: "Social Media" },
			{ label: "Web Marketing", value: "Web Marketing" },
			{ label: "Writing and Editing", value: "Writing and Editing" },
		],
		Operations: [
			{ label: "Facilities Management", value: "Facilities Management" },
			{ label: "Inventory Management", value: "Inventory Management" },
			{ label: "Logistics", value: "Logistics" },
			{ label: "Manufacturing", value: "Manufacturing" },
			{ label: "Packaging and Labelling", value: "Packaging and Labelling" },
			{ label: "Process Improvement", value: "Process Improvement" },
			{ label: "Procurement and Vendors", value: "Procurement and Vendors" },
			{
				label: "Program Design & Evaluation",
				value: "Program Design & Evaluation",
			},
			{ label: "Quality Management", value: "Quality Management" },
			{
				label: "Transportation and Delivery",
				value: "Transportation and Delivery",
			},
		],
		Sales: [
			{
				label: "Customer Service and CRM",
				value: "Customer Service and CRM",
			},
			{ label: "Govement Contracts", value: "Govement Contracts" },
			{ label: "Lead Generation", value: "Lead Generation" },
			{
				label: "Retail and Consumer Sales",
				value: "Retail and Consumer Sales",
			},
			{ label: "Selling Products", value: "Selling Products" },
			{ label: "Selling Services", value: "Selling Services" },
			{ label: "Wholesale and B2B Sales", value: "Wholesale and B2B Sales" },
		],
		Starting_up: [
			{ label: "Business Planning", value: "Business Planning" },
			{ label: "Franchising", value: "Franchising" },
			{ label: "Getting Started", value: "Getting Started" },
			{ label: "Legal Structure", value: "Legal Structure" },
			{ label: "Location and Zoning", value: "Location and Zoning" },
			{ label: "Sustainability", value: "Sustainability" },
		],
		Technology_and_Internet: [
			{ label: "Cloud Computing", value: "Cloud Computing" },
			{ label: "Cybersecurity", value: "Cybersecurity" },
			{ label: "Data Management", value: "Data Management" },
			{ label: "E-Conmerce", value: "E-Conmerce" },
			{ label: "Managing Technology", value: "Managing Technology" },
			{ label: "Technology and Internet", value: "Technology and Internet" },
			{ label: "Technology Plainning", value: "Technology Plainning" },
			{ label: "Telecommunications", value: "Telecommunications" },
			{ label: "Website Design", value: "Website Design" },
		],
	},
	VI: {
		Accounting_and_Finance: [
			{ label: "Kế toán", value: "Accounting" },
			{ label: "Kiểm toán", value: "Audits" },
			{ label: "Sổ sách", value: "Bookkeeping" },
			{ label: "Dòng tiền", value: "Cash Flow" },
			{ label: "Kế hoạch tài chính", value: "Financial Planning" },
			{ label: "Vay và Tài chính", value: "Loans and Financing" },
			{ label: "Thuế", value: "Taxes" },
			{ label: "Tài chính", value: "Financials" },
		],
		Human_Resources: [
			{
				label: "Lương thưởng và Phúc lợi",
				value: "Compensation and Benefits",
			},
			{
				label: "Nhân viên và Tư vấn",
				value: "Contractor and Consultants",
			},
			{ label: "Đào tạo nhân viên", value: "Employee Traning" },
			{ label: "Chính sách nhân sự", value: "Personnel Policies" },
			{ label: "Tuyển dụng", value: "Staffing and Recruiting" },
		],
		International: [
			{ label: "Hải quan và Thuế", value: "Custom and Tariffs" },
			{ label: "Xuất khẩu và Nhập khẩu", value: "Exporting and Importing" },
			{ label: "Thị trường toàn cầu", value: "Global Markets" },
			{ label: "Thuê ngoài", value: "Outsourcing" },
		],
		Law_and_Legal: [
			{ label: "Hợp đồng", value: "Contracts" },
			{ label: "Luật lao động", value: "Employee/Labour Law" },
			{ label: "Luật nhập cư", value: "Immigration Law" },
			{ label: "Sở hữu trí tuệ", value: "Intellectual Property" },
			{ label: "Luật tài sản", value: "Property Law" },
			{ label: "Luật thuế", value: "Tax Law" },
		],
		Management: [
			{ label: "Phát triển Ban quản trị", value: "Board Development" },
			{ label: "Bảo hiểm Doanh nghiệp", value: "Businness Insurance" },
			{ label: "Chiến lược Doanh nghiệp", value: "Businness Strategy" },
			{ label: "Gây quỹ", value: "Fundraising" },
			{
				label: "Tăng trưởng và Phát triển",
				value: "Growth and Development",
			},
			{ label: "Lãnh đạo", value: "Leadership" },
			{
				label: "Lập kế hoạch và Đặt mục tiêu",
				value: "Planning and Goal Setting",
			},
			{ label: "Quản lý dự án", value: "Project Management" },
			{
				label: "Cân bằng công việc và cuộc sống",
				value: "Work-life Balance",
			},
		],
		Marketing: [
			{
				label: "Quảng cáo và Khuyến mãi",
				value: "Advertising and Promotion",
			},
			{ label: "Thương hiệu và Định danh", value: "Branding and Identity" },
			{ label: "Phát triển kinh doanh", value: "Business Development" },
			{ label: "Phân phối", value: "Distribution" },
			{ label: "Nghiên cứu thị trường", value: "Market Research" },
			{ label: "Tài liệu tiếp thị", value: "Marketing Collateral" },
			{ label: "Giá cả", value: "Pricing" },
			{ label: "Phát triển sản phẩm", value: "Product Development" },
			{
				label: "Quan hệ công chúng và Truyền thông",
				value: "Puclic Relations and Media",
			},
			{ label: "Mạng xã hội", value: "Social Media" },
			{ label: "Tiếp thị trực tuyến", value: "Web Marketing" },
			{ label: "Viết và Biên tập", value: "Writing and Editing" },
		],
		Operations: [
			{ label: "Quản lý cơ sở vật chất", value: "Facilities Management" },
			{ label: "Quản lý hàng tồn", value: "Inventory Management" },
			{ label: "Vận chuyển", value: "Logistics" },
			{ label: "Sản xuất", value: "Manufacturing" },
			{ label: "Đóng gói và Nhãn", value: "Packaging and Labelling" },
			{ label: "Cải thiện quy trình", value: "Process Improvement" },
			{ label: "Mua sắm và Nhà cung cấp", value: "Procurement and Vendors" },
			{
				label: "Thiết kế và Đánh giá chương trình",
				value: "Program Design & Evaluation",
			},
			{ label: "Quản lý chất lượng", value: "Quality Management" },
			{
				label: "Vận chuyển và Giao hàng",
				value: "Transportation and Delivery",
			},
		],
		Sales: [
			{
				label: "Dịch vụ khách hàng và CRM",
				value: "Customer Service and CRM",
			},
			{ label: "Hợp đồng Chính phủ", value: "Govement Contracts" },
			{ label: "Tạo lead", value: "Lead Generation" },
			{
				label: "Bán lẻ và Bán hàng tiêu dùng",
				value: "Retail and Consumer Sales",
			},
			{ label: "Bán sản phẩm", value: "Selling Products" },
			{ label: "Bán dịch vụ", value: "Selling Services" },
			{ label: "Bán buôn và B2B Sales", value: "Wholesale and B2B Sales" },
		],
		Starting_up: [
			{ label: "Lập kế hoạch kinh doanh", value: "Business Planning" },
			{ label: "Mô hình kinh doanh", value: "Franchising" },
			{ label: "Bắt đầu", value: "Getting Started" },
			{ label: "Cấu trúc pháp lý", value: "Legal Structure" },
			{ label: "Vị trí và Quy hoạch", value: "Location and Zoning" },
			{ label: "Bền vững", value: "Sustainability" },
		],
		Technology_and_Internet: [
			{ label: "Điện toán đám mây", value: "Cloud Computing" },
			{ label: "Bảo mật mạng", value: "Cybersecurity" },
			{ label: "Quản lý dữ liệu", value: "Data Management" },
			{ label: "Thương mại điện tử", value: "E-Conmerce" },
			{ label: "Quản lý công nghệ", value: "Managing Technology" },
			{ label: "Công nghệ và Internet", value: "Technology and Internet" },
			{ label: "Lập kế hoạch công nghệ", value: "Technology Plainning" },
			{ label: "Viễn thông", value: "Telecommunications" },
			{ label: "Thiết kế trang web", value: "Website Design" },
		],
	},
	ZH: {
		Accounting_and_Finance: [
			{ label: "会计", value: "Accounting" },
			{ label: "审计", value: "Audits" },
			{ label: "簿记", value: "Bookkeeping" },
			{ label: "现金流", value: "Cash Flow" },
			{ label: "财务规划", value: "Financial Planning" },
			{ label: "贷款和融资", value: "Loans and Financing" },
			{ label: "税收", value: "Taxes" },
			{ label: "财务", value: "Financials" },
		],
		Human_Resources: [
			{
				label: "薪酬和福利",
				value: "Compensation and Benefits",
			},
			{
				label: "承包商和顾问",
				value: "Contractor and Consultants",
			},
			{ label: "员工培训", value: "Employee Traning" },
			{ label: "人事政策", value: "Personnel Policies" },
			{ label: "人员招聘", value: "Staffing and Recruiting" },
		],
		International: [
			{ label: "海关和关税", value: "Custom and Tariffs" },
			{ label: "出口和进口", value: "Exporting and Importing" },
			{ label: "全球市场", value: "Global Markets" },
			{ label: "外包", value: "Outsourcing" },
		],
		Law_and_Legal: [
			{ label: "合同", value: "Contracts" },
			{ label: "员工/劳工法", value: "Employee/Labour Law" },
			{ label: "移民法", value: "Immigration Law" },
			{ label: "知识产权", value: "Intellectual Property" },
			{ label: "财产法", value: "Property Law" },
			{ label: "税法", value: "Tax Law" },
		],
		Management: [
			{ label: "董事会发展", value: "Board Development" },
			{ label: "商业保险", value: "Businness Insurance" },
			{ label: "商业战略", value: "Businness Strategy" },
			{ label: "筹款", value: "Fundraising" },
			{ label: "增长和发展", value: "Growth and Development" },
			{ label: "领导力", value: "Leadership" },
			{ label: "计划和目标设定", value: "Planning and Goal Setting" },
			{ label: "项目管理", value: "Project Management" },
			{ label: "工作与生活平衡", value: "Work-life Balance" },
		],
		Marketing: [
			{
				label: "广告和促销",
				value: "Advertising and Promotion",
			},
			{ label: "品牌和身份", value: "Branding and Identity" },
			{ label: "业务发展", value: "Business Development" },
			{ label: "分销", value: "Distribution" },
			{ label: "市场研究", value: "Market Research" },
			{ label: "营销宣传", value: "Marketing Collateral" },
			{ label: "定价", value: "Pricing" },
			{ label: "产品开发", value: "Product Development" },
			{
				label: "公共关系和媒体",
				value: "Puclic Relations and Media",
			},
			{ label: "社交媒体", value: "Social Media" },
			{ label: "网络营销", value: "Web Marketing" },
			{ label: "写作和编辑", value: "Writing and Editing" },
		],
		Operations: [
			{ label: "设施管理", value: "Facilities Management" },
			{ label: "库存管理", value: "Inventory Management" },
			{ label: "物流", value: "Logistics" },
			{ label: "制造", value: "Manufacturing" },
			{ label: "包装和标签", value: "Packaging and Labelling" },
			{ label: "流程改进", value: "Process Improvement" },
			{ label: "采购和供应商", value: "Procurement and Vendors" },
			{
				label: "程序设计和评估",
				value: "Program Design & Evaluation",
			},
			{ label: "质量管理", value: "Quality Management" },
			{
				label: "运输和交付",
				value: "Transportation and Delivery",
			},
		],
		Sales: [
			{
				label: "客户服务和CRM",
				value: "Customer Service and CRM",
			},
			{ label: "政府合同", value: "Govement Contracts" },
			{ label: "潜在客户", value: "Lead Generation" },
			{
				label: "零售和消费者销售",
				value: "Retail and Consumer Sales",
			},
			{ label: "销售产品", value: "Selling Products" },
			{ label: "销售服务", value: "Selling Services" },
			{ label: "批发和B2B销售", value: "Wholesale and B2B Sales" },
		],
		Starting_up: [
			{ label: "商业计划", value: "Business Planning" },
			{ label: "特许经营", value: "Franchising" },
			{ label: "入门", value: "Getting Started" },
			{ label: "法律结构", value: "Legal Structure" },
			{ label: "位置和分区", value: "Location and Zoning" },
			{ label: "可持续性", value: "Sustainability" },
		],
		Technology_and_Internet: [
			{ label: "云计算", value: "Cloud Computing" },
			{ label: "网络安全", value: "Cybersecurity" },
			{ label: "数据管理", value: "Data Management" },
			{ label: "电子商务", value: "E-Conmerce" },
			{ label: "技术管理", value: "Managing Technology" },
			{ label: "技术和互联网", value: "Technology and Internet" },
			{ label: "技术规划", value: "Technology Plainning" },
			{ label: "电信", value: "Telecommunications" },
			{ label: "网站设计", value: "Website Design" },
		],
	},
};

export const STAGE = {
	EN: [
		{ label: "Idea Stage", value: "Idea Stage" },
		{ label: "Pre-seed Stage", value: "Pre-seed Stage" },
		{ label: "Seed Stage", value: "Seed Stage" },
		{ label: "Early Stage", value: "Early Stage" },
		{ label: "Growth Stage", value: "Growth Stage" },
		{ label: "Expansion Stage", value: "Expansion Stage" },
		{ label: "Mature Stage", value: "Mature Stage" },
	],
	VI: [
		{ label: "Giai đoạn ý tưởng", value: "Idea Stage" },
		{ label: "Giai đoạn trước hạt giống", value: "Pre-seed Stage" },
		{ label: "Giai đoạn hạt giống", value: "Seed Stage" },
		{ label: "Giai đoạn sớm", value: "Early Stage" },
		{ label: "Giai đoạn tăng trưởng", value: "Growth Stage" },
		{ label: "Giai đoạn mở rộng", value: "Expansion Stage" },
		{ label: "Giai đoạn chín", value: "Mature Stage" },
	],
	ZH: [
		{ label: "创意阶段", value: "Idea Stage" },
		{ label: "种子前阶段", value: "Pre-seed Stage" },
		{ label: "种子阶段", value: "Seed Stage" },
		{ label: "早期阶段", value: "Early Stage" },
		{ label: "增长阶段", value: "Growth Stage" },
		{ label: "扩张阶段", value: "Expansion Stage" },
		{ label: "成熟阶段", value: "Mature Stage" },
	],
};
export const ROLE = {
	EN: [
		{ label: "Founder", value: "Founder" },
		{ label: "Co-Founder", value: "Co-Founder" },
		{ label: "CEO", value: "CEO" },
		{ label: "CTO", value: "CTO" },
		{ label: "CFO", value: "CFO" },
		{ label: "CMO", value: "CMO" },
		{ label: "COO", value: "COO" },
		{ label: "CIO", value: "CIO" },
		{ label: "CISO", value: "CISO" },
		{ label: "CPO", value: "CPO" },
		{ label: "VP", value: "VP" },
		{ label: "Director", value: "Director" },
		{ label: "Manager", value: "Manager" },
		{ label: "Senior", value: "Senior" },
		{ label: "Junior", value: "Junior" },
		{ label: "Intern", value: "Intern" },
		{ label: "Freelancer", value: "Freelancer" },
	],
	VI: [
		{ label: "Người sáng lập", value: "Founder" },
		{ label: "Người đồng sáng lập", value: "Co-Founder" },
		{ label: "Giám đốc điều hành", value: "CEO" },
		{ label: "Giám đốc công nghệ", value: "CTO" },
		{ label: "Giám đốc tài chính", value: "CFO" },
		{ label: "Giám đốc tiếp thị", value: "CMO" },
		{ label: "Giám đốc điều hành", value: "COO" },
		{ label: "Giám đốc thông tin", value: "CIO" },
		{ label: "Giám đốc bảo mật thông tin", value: "CISO" },
		{ label: "Giám đốc sản phẩm", value: "CPO" },
		{ label: "Phó chủ tịch", value: "VP" },
		{ label: "Giám đốc", value: "Director" },
		{ label: "Quản lý", value: "Manager" },
		{ label: "Cao cấp", value: "Senior" },
		{ label: "Thực tập sinh", value: "Intern" },
		{ label: "Làm việc tự do", value: "Freelancer" },
	],
	ZH: [
		{ label: "创始人", value: "Founder" },
		{ label: "联合创始人", value: "Co-Founder" },
		{ label: "首席执行官", value: "CEO" },
		{ label: "首席技术官", value: "CTO" },
		{ label: "首席财务官", value: "CFO" },
		{ label: "首席营销官", value: "CMO" },
		{ label: "首席运营官", value: "COO" },
		{ label: "首席信息官", value: "CIO" },
		{ label: "首席信息安全官", value: "CISO" },
		{ label: "首席产品官", value: "CPO" },
		{ label: "副总裁", value: "VP" },
		{ label: "董事", value: "Director" },
		{ label: "经理", value: "Manager" },
		{ label: "高级", value: "Senior" },
		{ label: "实习生", value: "Intern" },
		{ label: "自由职业者", value: "Freelancer" },
	],
};

export const TEAM_ROLE = {
	EN: [
		{ label: "Core", value: "Core" },
		{ label: "Founding", value: "Founding" },
	],
	VI: [
		{ label: "Nhân viên cốt lõi", value: "Core" },
		{ label: "Nhân viên sáng lập", value: "Founding" },
	],
	ZH: [
		{ label: "核心员工", value: "Core" },
		{ label: "创始员工", value: "Founding" },
	],
};

export const LANGUAGE = {
	EN: [
		{ label: "Vietnamese", value: "Vietnamese" },
		{ label: "English", value: "English" },
		{ label: "Chinese", value: "Chinese" },
	],
	VI: [
		{ label: "Tiếng Việt", value: "Vietnamese" },
		{ label: "Tiếng Anh", value: "English" },
		{ label: "Tiếng Trung", value: "Chinese" },
	],
	ZH: [
		{ label: "越南语", value: "Vietnamese" },
		{ label: "英语", value: "English" },
		{ label: "中文", value: "Chinese" },
	],
};

export const AREA_OF_EXPERTISE_KEYS = Object.keys(AREA_OF_EXPERTISE);
